### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by KevinBatdorf** [KevinBatdorf/pattern-css#27]
Only a few things needed for this to be v1 ready.

- [x] Add reusable pattern/blocks tests.
- [x] Solve pattern duplication with scoped IDs (https://github.com/KevinBatdorf/per-page-css/pull/28)
- [x] Rebrand (See: https://github.com/KevinBatdorf/per-page-css/issues/26)
- [x] Update the lightening css library
- [x] Evaluate missing features, etc

After that, I will try again to get it listed on w.org. Given they have a new team now they could be more understanding of the safety this plugin provides over the others. 

If anyone reading has any ideas/tips on the last part, reply here or dm me somewhere.
